# Generated by Django 3.1 on 2020-08-15 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_auto_20200815_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='dateco_mpleted',
            new_name='date_completed',
        ),
    ]
